package com.wao.iptv

data class LangDef(val code: String, val native: String, val flag: String)

val APP_LANGUAGES = listOf(
    LangDef("en", "English", "🇬🇧"),
    LangDef("ur-roman", "Roman Urdu", "🇵🇰"),
    LangDef("ur", "اردو", "🇵🇰"),
    LangDef("ar", "العربية", "🇸🇦"),
    LangDef("ps", "پښتو", "🇦🇫"),
    LangDef("sd", "سنڌي", "🇵🇰"),
    LangDef("es", "Español", "🇪🇸"),
    LangDef("fr", "Français", "🇫🇷"),
    LangDef("hi", "हिन्दी", "🇮🇳"),
    LangDef("zh", "中文", "🇨🇳"),
    LangDef("ru", "Русский", "🇷🇺")
)

// App ki ab tak selected language — connection errors jaisi jagah jahan direct
// Composable context nahi hota, wahan isi se translate hota hai.
@Volatile
var currentLang: String = "en"

private val EN = mapOf(
    "tagline" to "Stream Anytime • Anywhere",
    "tab_xtream" to "Xtream Codes",
    "tab_m3u" to "M3U Playlist",
    "label_server" to "Server URL",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "Username",
    "ph_username" to "Enter Xtream username",
    "label_password" to "Password",
    "btn_connect" to "CONNECT & LOAD CHANNELS",
    "btn_loadm3u" to "LOAD M3U PLAYLIST",
    "powered_by" to "Powered by MediaCodec HW+ & ExoPlayer",
    "nav_home" to "Home",
    "nav_live" to "Live TV",
    "nav_vod" to "VOD",
    "nav_settings" to "Settings",
    "settings_title" to "App Settings & Decoder",
    "account" to "Account",
    "player_engine" to "Player Engine",
    "buffer_mode" to "Buffer / Streaming Mode",
    "parental_lock" to "Parental Lock (4-Digit PIN)",
    "logout" to "Logout / Change Server",
    "test_connection" to "Test Connection",
    "app_update" to "App Update",
    "select_language" to "Select Language",
    "loading_live" to "LOADING LIVE TV...",
    "loading_movies" to "LOADING MOVIES...",
    "loading_series" to "LOADING SERIES...",
    "connecting" to "CONNECTING...",
    "err_fill_xtream" to "Please fill Server URL, Username and Password",
    "err_fill_m3u" to "Please paste the M3U link",
    "err_bad_response" to "Server sent an invalid response. Please check the Xtream API.",
    "err_wrong_credentials" to "Incorrect username or password",
    "err_account_status" to "Account is {status}",
    "err_invalid_m3u" to "This is not a valid M3U playlist",
    "err_no_content" to "No channels or movies found on this account",
    "err_no_server" to "Server not found. Check the URL and your internet.",
    "err_timeout" to "Server did not respond in time (timeout).",
    "err_ssl" to "SSL/HTTPS issue. Try http:// instead.",
    "err_bad_url" to "Server URL is not valid.",
    "err_connect_failed" to "Could not connect."
)

private val UR_ROMAN = mapOf(
    "tagline" to "Kabhi Bhi • Kahin Bhi Dekhein",
    "tab_xtream" to "Xtream Codes",
    "tab_m3u" to "M3U Playlist",
    "label_server" to "Server URL",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "Username",
    "ph_username" to "Xtream username likhein",
    "label_password" to "Password",
    "btn_connect" to "CONNECT KAREIN & CHANNELS LOAD KAREIN",
    "btn_loadm3u" to "M3U PLAYLIST LOAD KAREIN",
    "powered_by" to "MediaCodec HW+ & ExoPlayer se chal raha hai",
    "nav_home" to "Home",
    "nav_live" to "Live TV",
    "nav_vod" to "VOD",
    "nav_settings" to "Settings",
    "settings_title" to "App Settings & Decoder",
    "account" to "Account",
    "player_engine" to "Player Engine",
    "buffer_mode" to "Buffer / Streaming Mode",
    "parental_lock" to "Parental Lock (4-Digit PIN)",
    "logout" to "Logout / Server Change Karein",
    "test_connection" to "Connection Test Karein",
    "app_update" to "App Update",
    "select_language" to "Zaban Chunein",
    "loading_live" to "LIVE TV LOAD HO RAHA HAI...",
    "loading_movies" to "MOVIES LOAD HO RAHI HAIN...",
    "loading_series" to "SERIES LOAD HO RAHI HAIN...",
    "connecting" to "CONNECT HO RAHA HAI...",
    "err_fill_xtream" to "Server URL, username aur password teeno bharein",
    "err_fill_m3u" to "M3U link paste karein",
    "err_bad_response" to "Server ne sahi jawab nahi diya. Xtream API check karein.",
    "err_wrong_credentials" to "Username ya password ghalat hai",
    "err_account_status" to "Account {status} hai",
    "err_invalid_m3u" to "Ye valid M3U playlist nahi hai",
    "err_no_content" to "Is account me koi channel ya movie nahi mili",
    "err_no_server" to "Server nahi mil raha. URL aur internet check karein.",
    "err_timeout" to "Server ne waqt par jawab nahi diya (timeout).",
    "err_ssl" to "SSL/HTTPS ka masla hai. http:// try karein.",
    "err_bad_url" to "Server URL sahi nahi hai.",
    "err_connect_failed" to "Connect nahi ho saka."
)

private val UR = mapOf(
    "tagline" to "کسی بھی وقت • کہیں بھی دیکھیں",
    "tab_xtream" to "ایکسٹریم کوڈز",
    "tab_m3u" to "ایم تھری یو پلے لسٹ",
    "label_server" to "سرور یو آر ایل",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "یوزر نیم",
    "ph_username" to "ایکسٹریم یوزر نیم درج کریں",
    "label_password" to "پاسورڈ",
    "btn_connect" to "کنیکٹ کریں اور چینلز لوڈ کریں",
    "btn_loadm3u" to "ایم تھری یو پلے لسٹ لوڈ کریں",
    "powered_by" to "میڈیا کوڈیک ایچ ڈبلیو+ اور ایکسو پلیئر سے چلتا ہے",
    "nav_home" to "ہوم",
    "nav_live" to "لائیو ٹی وی",
    "nav_vod" to "وی او ڈی",
    "nav_settings" to "سیٹنگز",
    "settings_title" to "ایپ سیٹنگز اور ڈی کوڈر",
    "account" to "اکاؤنٹ",
    "player_engine" to "پلیئر انجن",
    "buffer_mode" to "بفر / اسٹریمنگ موڈ",
    "parental_lock" to "پیرنٹل لاک (4 ہندسوں کا پن)",
    "logout" to "لاگ آؤٹ / سرور تبدیل کریں",
    "test_connection" to "کنکشن ٹیسٹ کریں",
    "app_update" to "ایپ اپڈیٹ",
    "select_language" to "زبان منتخب کریں",
    "loading_live" to "لائیو ٹی وی لوڈ ہو رہا ہے...",
    "loading_movies" to "موویز لوڈ ہو رہی ہیں...",
    "loading_series" to "سیریز لوڈ ہو رہی ہیں...",
    "connecting" to "کنیکٹ ہو رہا ہے...",
    "err_fill_xtream" to "سرور یو آر ایل، یوزر نیم اور پاسورڈ تینوں بھریں",
    "err_fill_m3u" to "ایم تھری یو لنک پیسٹ کریں",
    "err_bad_response" to "سرور نے درست جواب نہیں دیا۔ Xtream API چیک کریں۔",
    "err_wrong_credentials" to "یوزر نیم یا پاسورڈ غلط ہے",
    "err_account_status" to "اکاؤنٹ {status} ہے",
    "err_invalid_m3u" to "یہ درست M3U پلے لسٹ نہیں ہے",
    "err_no_content" to "اس اکاؤنٹ میں کوئی چینل یا مووی نہیں ملی",
    "err_no_server" to "سرور نہیں مل رہا۔ یو آر ایل اور انٹرنیٹ چیک کریں۔",
    "err_timeout" to "سرور نے وقت پر جواب نہیں دیا (ٹائم آؤٹ)۔",
    "err_ssl" to "SSL/HTTPS کا مسئلہ ہے۔ http:// آزمائیں۔",
    "err_bad_url" to "سرور یو آر ایل درست نہیں ہے۔",
    "err_connect_failed" to "کنیکٹ نہیں ہو سکا۔"
)

private val AR = mapOf(
    "tagline" to "شاهد في أي وقت ومن أي مكان",
    "tab_xtream" to "رموز Xtream",
    "tab_m3u" to "قائمة M3U",
    "label_server" to "رابط الخادم",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "اسم المستخدم",
    "ph_username" to "أدخل اسم مستخدم Xtream",
    "label_password" to "كلمة المرور",
    "btn_connect" to "اتصل وحمّل القنوات",
    "btn_loadm3u" to "تحميل قائمة M3U",
    "powered_by" to "مدعوم بواسطة MediaCodec HW+ و ExoPlayer",
    "nav_home" to "الرئيسية",
    "nav_live" to "البث المباشر",
    "nav_vod" to "عند الطلب",
    "nav_settings" to "الإعدادات",
    "settings_title" to "إعدادات التطبيق وفك التشفير",
    "account" to "الحساب",
    "player_engine" to "محرك المشغل",
    "buffer_mode" to "وضع التخزين المؤقت / البث",
    "parental_lock" to "القفل الأبوي (رمز من 4 أرقام)",
    "logout" to "تسجيل الخروج / تغيير الخادم",
    "test_connection" to "اختبار الاتصال",
    "app_update" to "تحديث التطبيق",
    "select_language" to "اختر اللغة",
    "loading_live" to "جارٍ تحميل البث المباشر...",
    "loading_movies" to "جارٍ تحميل الأفلام...",
    "loading_series" to "جارٍ تحميل المسلسلات...",
    "connecting" to "جارٍ الاتصال...",
    "err_fill_xtream" to "يرجى ملء رابط الخادم واسم المستخدم وكلمة المرور",
    "err_fill_m3u" to "يرجى لصق رابط M3U",
    "err_bad_response" to "استجابة غير صالحة من الخادم. يرجى التحقق من Xtream API.",
    "err_wrong_credentials" to "اسم المستخدم أو كلمة المرور غير صحيحة",
    "err_account_status" to "الحساب {status}",
    "err_invalid_m3u" to "هذه ليست قائمة M3U صالحة",
    "err_no_content" to "لم يتم العثور على قنوات أو أفلام في هذا الحساب",
    "err_no_server" to "الخادم غير موجود. تحقق من الرابط والإنترنت.",
    "err_timeout" to "لم يستجب الخادم في الوقت المحدد.",
    "err_ssl" to "مشكلة في SSL/HTTPS. جرّب http:// بدلاً منه.",
    "err_bad_url" to "رابط الخادم غير صالح.",
    "err_connect_failed" to "تعذر الاتصال."
)

private val PS = mapOf(
    "tagline" to "هر وخت • هر ځای وګورئ",
    "tab_xtream" to "Xtream کوډونه",
    "tab_m3u" to "M3U لیست",
    "label_server" to "د سرور یو آر ال",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "کارن نوم",
    "ph_username" to "د Xtream کارن نوم ولیکئ",
    "label_password" to "پاسورډ",
    "btn_connect" to "وصل شئ او چینلونه لوډ کړئ",
    "btn_loadm3u" to "M3U لیست لوډ کړئ",
    "powered_by" to "د MediaCodec HW+ او ExoPlayer له لارې",
    "nav_home" to "کور",
    "nav_live" to "ژوندی ټی وی",
    "nav_vod" to "VOD",
    "nav_settings" to "تنظیمات",
    "settings_title" to "د اپلیکیشن تنظیمات",
    "account" to "حساب",
    "player_engine" to "د پلیر انجن",
    "buffer_mode" to "بفر / سټریمینګ موډ",
    "parental_lock" to "د والدینو تړون (۴ عددي پن)",
    "logout" to "وتل / سرور بدلول",
    "test_connection" to "د نښلون ازموینه",
    "app_update" to "د اپ تازه کول",
    "select_language" to "ژبه وټاکئ",
    "loading_live" to "ژوندی ټی وی لوډ کیږي...",
    "loading_movies" to "فلمونه لوډ کیږي...",
    "loading_series" to "سیریزونه لوډ کیږي...",
    "connecting" to "نښلول کیږي...",
    "err_fill_xtream" to "د سرور یو آر ال، کارن نوم او پاسورډ ډک کړئ",
    "err_fill_m3u" to "د M3U لینک پیسټ کړئ",
    "err_bad_response" to "سرور سم ځواب ور نکړ. Xtream API وګورئ.",
    "err_wrong_credentials" to "کارن نوم یا پاسورډ غلط دی",
    "err_account_status" to "حساب {status} دی",
    "err_invalid_m3u" to "دا سمه M3U لیست نه ده",
    "err_no_content" to "په دې حساب کې هیڅ چینل یا فلم ونه موندل شو",
    "err_no_server" to "سرور ونه موندل شو. یو آر ال او انټرنیټ وګورئ.",
    "err_timeout" to "سرور په وخت ځواب ور نکړ.",
    "err_ssl" to "د SSL/HTTPS ستونزه. http:// وکوښښئ.",
    "err_bad_url" to "د سرور یو آر ال سم نه دی.",
    "err_connect_failed" to "وصل نشو."
)

private val SD = mapOf(
    "tagline" to "ڪنهن به وقت • ڪٿي به ڏسو",
    "tab_xtream" to "Xtream ڪوڊس",
    "tab_m3u" to "M3U پليلسٽ",
    "label_server" to "سرور يو آر ايل",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "يوزرنيم",
    "ph_username" to "Xtream يوزرنيم لکو",
    "label_password" to "پاسورڊ",
    "btn_connect" to "ڪنيڪٽ ڪريو ۽ چينل لوڊ ڪريو",
    "btn_loadm3u" to "M3U پليلسٽ لوڊ ڪريو",
    "powered_by" to "MediaCodec HW+ ۽ ExoPlayer جي مدد سان",
    "nav_home" to "هوم",
    "nav_live" to "لائيو ٽي وي",
    "nav_vod" to "VOD",
    "nav_settings" to "سيٽنگون",
    "settings_title" to "ايپ سيٽنگون",
    "account" to "اڪائونٽ",
    "player_engine" to "پليئر انجڻ",
    "buffer_mode" to "بفر / اسٽريمنگ موڊ",
    "parental_lock" to "پيرنٽل لاڪ (4 عدد پن)",
    "logout" to "لاگ آئوٽ / سرور تبديل ڪريو",
    "test_connection" to "ڪنيڪشن ٽيسٽ ڪريو",
    "app_update" to "ايپ اپڊيٽ",
    "select_language" to "ٻولي چونڊيو",
    "loading_live" to "لائيو ٽي وي لوڊ ٿي رهيو آهي...",
    "loading_movies" to "موويز لوڊ ٿي رهيون آهن...",
    "loading_series" to "سيريز لوڊ ٿي رهيون آهن...",
    "connecting" to "ڪنيڪٽ ٿي رهيو آهي...",
    "err_fill_xtream" to "سرور يو آر ايل، يوزرنيم ۽ پاسورڊ ٽيئي ڀريو",
    "err_fill_m3u" to "M3U لنڪ پيسٽ ڪريو",
    "err_bad_response" to "سرور صحيح جواب نه ڏنو. Xtream API چيڪ ڪريو.",
    "err_wrong_credentials" to "يوزرنيم يا پاسورڊ غلط آهي",
    "err_account_status" to "اڪائونٽ {status} آهي",
    "err_invalid_m3u" to "هي صحيح M3U پليلسٽ ناهي",
    "err_no_content" to "هن اڪائونٽ ۾ ڪو چينل يا مووي نه ملي",
    "err_no_server" to "سرور نه ملي رهيو آهي. يو آر ايل ۽ انٽرنيٽ چيڪ ڪريو.",
    "err_timeout" to "سرور وقت تي جواب نه ڏنو.",
    "err_ssl" to "SSL/HTTPS جو مسئلو آهي. http:// آزمايو.",
    "err_bad_url" to "سرور يو آر ايل صحيح ناهي.",
    "err_connect_failed" to "ڪنيڪٽ نه ٿي سگھيو."
)

private val ES = mapOf(
    "tagline" to "Mira en cualquier momento y lugar",
    "tab_xtream" to "Códigos Xtream",
    "tab_m3u" to "Lista M3U",
    "label_server" to "URL del servidor",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "Usuario",
    "ph_username" to "Ingresa tu usuario Xtream",
    "label_password" to "Contraseña",
    "btn_connect" to "CONECTAR Y CARGAR CANALES",
    "btn_loadm3u" to "CARGAR LISTA M3U",
    "powered_by" to "Desarrollado con MediaCodec HW+ y ExoPlayer",
    "nav_home" to "Inicio",
    "nav_live" to "TV en vivo",
    "nav_vod" to "VOD",
    "nav_settings" to "Ajustes",
    "settings_title" to "Ajustes de la app y decodificador",
    "account" to "Cuenta",
    "player_engine" to "Motor del reproductor",
    "buffer_mode" to "Modo de buffer / transmisión",
    "parental_lock" to "Control parental (PIN de 4 dígitos)",
    "logout" to "Cerrar sesión / Cambiar servidor",
    "test_connection" to "Probar conexión",
    "app_update" to "Actualización de la app",
    "select_language" to "Seleccionar idioma",
    "loading_live" to "CARGANDO TV EN VIVO...",
    "loading_movies" to "CARGANDO PELÍCULAS...",
    "loading_series" to "CARGANDO SERIES...",
    "connecting" to "CONECTANDO...",
    "err_fill_xtream" to "Completa la URL del servidor, usuario y contraseña",
    "err_fill_m3u" to "Pega el enlace M3U",
    "err_bad_response" to "El servidor envió una respuesta inválida. Verifica la API Xtream.",
    "err_wrong_credentials" to "Usuario o contraseña incorrectos",
    "err_account_status" to "La cuenta está {status}",
    "err_invalid_m3u" to "Esta no es una lista M3U válida",
    "err_no_content" to "No se encontraron canales ni películas en esta cuenta",
    "err_no_server" to "Servidor no encontrado. Verifica la URL e internet.",
    "err_timeout" to "El servidor no respondió a tiempo.",
    "err_ssl" to "Problema de SSL/HTTPS. Prueba con http://.",
    "err_bad_url" to "La URL del servidor no es válida.",
    "err_connect_failed" to "No se pudo conectar."
)

private val FR = mapOf(
    "tagline" to "Regardez à tout moment, n'importe où",
    "tab_xtream" to "Codes Xtream",
    "tab_m3u" to "Playlist M3U",
    "label_server" to "URL du serveur",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "Nom d'utilisateur",
    "ph_username" to "Entrez le nom d'utilisateur Xtream",
    "label_password" to "Mot de passe",
    "btn_connect" to "CONNECTER ET CHARGER LES CHAÎNES",
    "btn_loadm3u" to "CHARGER LA PLAYLIST M3U",
    "powered_by" to "Propulsé par MediaCodec HW+ et ExoPlayer",
    "nav_home" to "Accueil",
    "nav_live" to "TV en direct",
    "nav_vod" to "VOD",
    "nav_settings" to "Paramètres",
    "settings_title" to "Paramètres de l'app et décodeur",
    "account" to "Compte",
    "player_engine" to "Moteur du lecteur",
    "buffer_mode" to "Mode mémoire tampon / diffusion",
    "parental_lock" to "Contrôle parental (code à 4 chiffres)",
    "logout" to "Déconnexion / Changer de serveur",
    "test_connection" to "Tester la connexion",
    "app_update" to "Mise à jour de l'app",
    "select_language" to "Choisir la langue",
    "loading_live" to "CHARGEMENT DE LA TV EN DIRECT...",
    "loading_movies" to "CHARGEMENT DES FILMS...",
    "loading_series" to "CHARGEMENT DES SÉRIES...",
    "connecting" to "CONNEXION...",
    "err_fill_xtream" to "Veuillez remplir l'URL du serveur, le nom d'utilisateur et le mot de passe",
    "err_fill_m3u" to "Veuillez coller le lien M3U",
    "err_bad_response" to "Le serveur a renvoyé une réponse invalide. Vérifiez l'API Xtream.",
    "err_wrong_credentials" to "Nom d'utilisateur ou mot de passe incorrect",
    "err_account_status" to "Le compte est {status}",
    "err_invalid_m3u" to "Ce n'est pas une playlist M3U valide",
    "err_no_content" to "Aucune chaîne ni film trouvé sur ce compte",
    "err_no_server" to "Serveur introuvable. Vérifiez l'URL et votre connexion.",
    "err_timeout" to "Le serveur n'a pas répondu à temps.",
    "err_ssl" to "Problème SSL/HTTPS. Essayez http:// à la place.",
    "err_bad_url" to "L'URL du serveur n'est pas valide.",
    "err_connect_failed" to "Connexion impossible."
)

private val HI = mapOf(
    "tagline" to "कभी भी, कहीं भी देखें",
    "tab_xtream" to "Xtream कोड्स",
    "tab_m3u" to "M3U प्लेलिस्ट",
    "label_server" to "सर्वर यूआरएल",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "यूज़रनेम",
    "ph_username" to "Xtream यूज़रनेम दर्ज करें",
    "label_password" to "पासवर्ड",
    "btn_connect" to "कनेक्ट करें और चैनल लोड करें",
    "btn_loadm3u" to "M3U प्लेलिस्ट लोड करें",
    "powered_by" to "MediaCodec HW+ और ExoPlayer द्वारा संचालित",
    "nav_home" to "होम",
    "nav_live" to "लाइव टीवी",
    "nav_vod" to "VOD",
    "nav_settings" to "सेटिंग्स",
    "settings_title" to "ऐप सेटिंग्स और डिकोडर",
    "account" to "खाता",
    "player_engine" to "प्लेयर इंजन",
    "buffer_mode" to "बफर / स्ट्रीमिंग मोड",
    "parental_lock" to "पैरेंटल लॉक (4 अंकों का पिन)",
    "logout" to "लॉगआउट / सर्वर बदलें",
    "test_connection" to "कनेक्शन टेस्ट करें",
    "app_update" to "ऐप अपडेट",
    "select_language" to "भाषा चुनें",
    "loading_live" to "लाइव टीवी लोड हो रहा है...",
    "loading_movies" to "मूवीज़ लोड हो रही हैं...",
    "loading_series" to "सीरीज़ लोड हो रही हैं...",
    "connecting" to "कनेक्ट हो रहा है...",
    "err_fill_xtream" to "सर्वर यूआरएल, यूज़रनेम और पासवर्ड तीनों भरें",
    "err_fill_m3u" to "M3U लिंक पेस्ट करें",
    "err_bad_response" to "सर्वर से गलत जवाब मिला। Xtream API जांचें।",
    "err_wrong_credentials" to "यूज़रनेम या पासवर्ड गलत है",
    "err_account_status" to "खाता {status} है",
    "err_invalid_m3u" to "यह मान्य M3U प्लेलिस्ट नहीं है",
    "err_no_content" to "इस खाते में कोई चैनल या मूवी नहीं मिली",
    "err_no_server" to "सर्वर नहीं मिला। यूआरएल और इंटरनेट जांचें।",
    "err_timeout" to "सर्वर ने समय पर जवाब नहीं दिया।",
    "err_ssl" to "SSL/HTTPS समस्या है। http:// आज़माएं।",
    "err_bad_url" to "सर्वर यूआरएल सही नहीं है।",
    "err_connect_failed" to "कनेक्ट नहीं हो सका।"
)

private val ZH = mapOf(
    "tagline" to "随时随地观看",
    "tab_xtream" to "Xtream 代码",
    "tab_m3u" to "M3U 播放列表",
    "label_server" to "服务器地址",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "用户名",
    "ph_username" to "输入 Xtream 用户名",
    "label_password" to "密码",
    "btn_connect" to "连接并加载频道",
    "btn_loadm3u" to "加载 M3U 播放列表",
    "powered_by" to "由 MediaCodec HW+ 和 ExoPlayer 提供支持",
    "nav_home" to "首页",
    "nav_live" to "直播",
    "nav_vod" to "点播",
    "nav_settings" to "设置",
    "settings_title" to "应用设置与解码器",
    "account" to "账户",
    "player_engine" to "播放引擎",
    "buffer_mode" to "缓冲/流媒体模式",
    "parental_lock" to "家长锁（4位密码）",
    "logout" to "退出登录 / 更换服务器",
    "test_connection" to "测试连接",
    "app_update" to "应用更新",
    "select_language" to "选择语言",
    "loading_live" to "正在加载直播...",
    "loading_movies" to "正在加载电影...",
    "loading_series" to "正在加载剧集...",
    "connecting" to "正在连接...",
    "err_fill_xtream" to "请填写服务器地址、用户名和密码",
    "err_fill_m3u" to "请粘贴 M3U 链接",
    "err_bad_response" to "服务器返回了无效响应。请检查 Xtream API。",
    "err_wrong_credentials" to "用户名或密码错误",
    "err_account_status" to "账户状态：{status}",
    "err_invalid_m3u" to "这不是有效的 M3U 播放列表",
    "err_no_content" to "此账户未找到频道或电影",
    "err_no_server" to "找不到服务器。请检查地址和网络。",
    "err_timeout" to "服务器响应超时。",
    "err_ssl" to "SSL/HTTPS 问题，请尝试使用 http://。",
    "err_bad_url" to "服务器地址无效。",
    "err_connect_failed" to "无法连接。"
)

private val RU = mapOf(
    "tagline" to "Смотрите в любое время и в любом месте",
    "tab_xtream" to "Коды Xtream",
    "tab_m3u" to "Плейлист M3U",
    "label_server" to "URL сервера",
    "ph_server" to "http://my-iptv-server.com:8080",
    "label_username" to "Имя пользователя",
    "ph_username" to "Введите имя пользователя Xtream",
    "label_password" to "Пароль",
    "btn_connect" to "ПОДКЛЮЧИТЬСЯ И ЗАГРУЗИТЬ КАНАЛЫ",
    "btn_loadm3u" to "ЗАГРУЗИТЬ ПЛЕЙЛИСТ M3U",
    "powered_by" to "Работает на MediaCodec HW+ и ExoPlayer",
    "nav_home" to "Главная",
    "nav_live" to "Прямой эфир",
    "nav_vod" to "VOD",
    "nav_settings" to "Настройки",
    "settings_title" to "Настройки приложения и декодер",
    "account" to "Аккаунт",
    "player_engine" to "Движок плеера",
    "buffer_mode" to "Режим буферизации / потока",
    "parental_lock" to "Родительский контроль (4-значный PIN)",
    "logout" to "Выйти / Сменить сервер",
    "test_connection" to "Проверить соединение",
    "app_update" to "Обновление приложения",
    "select_language" to "Выбрать язык",
    "loading_live" to "ЗАГРУЗКА ПРЯМОГО ЭФИРА...",
    "loading_movies" to "ЗАГРУЗКА ФИЛЬМОВ...",
    "loading_series" to "ЗАГРУЗКА СЕРИАЛОВ...",
    "connecting" to "ПОДКЛЮЧЕНИЕ...",
    "err_fill_xtream" to "Заполните URL сервера, имя пользователя и пароль",
    "err_fill_m3u" to "Вставьте ссылку M3U",
    "err_bad_response" to "Сервер вернул неверный ответ. Проверьте Xtream API.",
    "err_wrong_credentials" to "Неверное имя пользователя или пароль",
    "err_account_status" to "Статус аккаунта: {status}",
    "err_invalid_m3u" to "Это не действительный плейлист M3U",
    "err_no_content" to "На этом аккаунте не найдено каналов или фильмов",
    "err_no_server" to "Сервер не найден. Проверьте URL и интернет.",
    "err_timeout" to "Сервер не ответил вовремя.",
    "err_ssl" to "Проблема с SSL/HTTPS. Попробуйте http://.",
    "err_bad_url" to "Неверный URL сервера.",
    "err_connect_failed" to "Не удалось подключиться."
)

private val ALL_LANGS: Map<String, Map<String, String>> = mapOf(
    "en" to EN,
    "ur-roman" to UR_ROMAN,
    "ur" to UR,
    "ar" to AR,
    "ps" to PS,
    "sd" to SD,
    "es" to ES,
    "fr" to FR,
    "hi" to HI,
    "zh" to ZH,
    "ru" to RU
)

fun tr(lang: String, key: String): String {
    val table = ALL_LANGS[lang] ?: EN
    return table[key] ?: EN[key] ?: key
}

fun isRtlLang(lang: String): Boolean = lang == "ar" || lang == "ur" || lang == "ps" || lang == "sd"
